#define WIN32_LEAN_AND_MEAN
#include "winsock2.h"
#include <strsafe.h>
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <conio.h>
#include <memory.h>
#include <limits.h>
#include <math.h>
#include "defines.h"
//#include "swfdefs.h"
#include "macros.h"
//#include "ftpmacros.h"
//#include "swfmacros.h"
#include "structs.h"
//#include "swfstructs.h"
#include "protos.h"
